### ISSUE TITLE
More than one launcher activity

### ISSUE THREAD

**Issue by draganczukp** [Programowanie-urzadzen-mobilnych/android-app#83]
After adding a launcher activity for Presentation module, the old auto-generated "Hello World" activity is still present. This causes problems when launching, since Android Studio launches the old activity.

**Comment by Legut** [comment]
Actually this is intentional. As far as I know we work in our modules only. So we didn't want to change anything in root. Thats why we declared MainActivity of our module as launcher. But this change is only in AndroidManifest of our module. Later while we will be fusing our work, we will change that. For now i am closing this issue.
